"""Add scores table

Revision ID: 33a432847899
Revises: 0f8b124367a2
Create Date: 2026-02-08 23:22:43.282931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33a432847899'
down_revision: Union[str, Sequence[str], None] = '0f8b124367a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_content_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('score_type', sa.String(), nullable=False),
    sa.Column('correctness', sa.Float(), nullable=False),
    sa.Column('conceptual_depth', sa.Float(), nullable=False),
    sa.Column('reasoning_quality', sa.Float(), nullable=False),
    sa.Column('confidence_alignment', sa.Float(), nullable=False),
    sa.Column('misconceptions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_content_id'], ['module_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_module_content_id'), 'scores', ['module_content_id'], unique=False)
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_module_content_id'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
