"""Add course_modules table

Revision ID: 5611bc810456
Revises: dbad1f13afd5
Create Date: 2026-02-09 22:57:31.978199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5611bc810456'
down_revision: Union[str, Sequence[str], None] = 'dbad1f13afd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Clean recreate of course_modules to ensure correct schema and UUIDs
    # Drop if exists (Alembic saw it, so it exists)
    op.drop_table('course_modules')
    
    op.create_table('course_modules',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('course_id', sa.UUID(), nullable=False),
        sa.Column('module_content_id', sa.UUID(), nullable=False),
        sa.Column('module_order', sa.Integer(), nullable=True, default=0),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['module_content_id'], ['module_content.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Do NOT drop module_context from module_content
    # op.drop_column('module_content', 'module_context') 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_content', sa.Column('module_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('course_modules', sa.Column('module_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_modules', type_='foreignkey')
    op.drop_constraint(None, 'course_modules', type_='foreignkey')
    op.alter_column('course_modules', 'course_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('course_modules', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_column('course_modules', 'module_order')
    op.drop_column('course_modules', 'module_content_id')
    # ### end Alembic commands ###
