"""add_correctness_score_to_question_attempts

Revision ID: ca8338269b7f
Revises: ca8cbd639bb4
Create Date: 2026-02-09 16:08:10.790138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca8338269b7f'
down_revision: Union[str, Sequence[str], None] = 'ca8cbd639bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_content', 'module_context')
    op.add_column('question_attempts', sa.Column('correctness_score', sa.Numeric(precision=3, scale=2), nullable=True))
    op.drop_index(op.f('ix_user_module_completion_module_id'), table_name='user_module_completion')
    op.drop_index(op.f('ix_user_module_completion_user_id'), table_name='user_module_completion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_module_completion_user_id'), 'user_module_completion', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_module_completion_module_id'), 'user_module_completion', ['module_id'], unique=False)
    op.drop_column('question_attempts', 'correctness_score')
    op.add_column('module_content', sa.Column('module_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
