"""update_confidence_scale_to_10

Revision ID: ca8cbd639bb4
Revises: 1c72dfdc0337
Create Date: 2026-02-09 15:49:42.815212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca8cbd639bb4'
down_revision: Union[str, Sequence[str], None] = '1c72dfdc0337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_attempts', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_attempts', 'confidence',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
