"""Add courses and course users

Revision ID: dbad1f13afd5
Revises: de7cd47fe727
Create Date: 2026-02-09 20:41:00.378365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbad1f13afd5'
down_revision: Union[str, Sequence[str], None] = 'de7cd47fe727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop course_module if it exists (Alembic detected it, so it should)
    op.drop_table('course_module')

    # Drop course_users to recreate with UUID id
    op.drop_table('course_users')
    
    # Recreate course_users
    op.create_table('course_users',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.UUID(), nullable=False),
        sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Modify courses
    # Add title with default to avoid null constraint error on existing rows
    op.add_column('courses', sa.Column('title', sa.String(), server_default='Untitled Course', nullable=False))
    op.add_column('courses', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('courses', 'name')
    
    # Remove default from title after creation if needed (optional, keeping it simple)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'title')
    op.add_column('course_users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course_users', type_='foreignkey')
    op.drop_constraint(None, 'course_users', type_='foreignkey')
    op.alter_column('course_users', 'course_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('course_users', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('course_users', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_column('course_users', 'joined_at')
    op.create_table('course_module',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_module_course_id_fkey')),
    sa.ForeignKeyConstraint(['module_id'], ['module_content.id'], name=op.f('course_module_module_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_module_pkey'))
    )
    # ### end Alembic commands ###
