"""verify_correctness_score

Revision ID: de7cd47fe727
Revises: ca8338269b7f
Create Date: 2026-02-09 16:13:06.520578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de7cd47fe727'
down_revision: Union[str, Sequence[str], None] = 'ca8338269b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_content', 'module_context')
    op.drop_index(op.f('ix_user_module_completion_module_id'), table_name='user_module_completion')
    op.drop_index(op.f('ix_user_module_completion_user_id'), table_name='user_module_completion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_module_completion_user_id'), 'user_module_completion', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_module_completion_module_id'), 'user_module_completion', ['module_id'], unique=False)
    op.add_column('module_content', sa.Column('module_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
